---

  - name: camera video stream service descriptor
    become: yes
    copy: src="camera_stream.service" dest="/etc/systemd/system/camera_stream.service"

  - name: enable and start camera video stream service
    become: yes
    service: name=camera_stream enabled=yes state=started
